import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke, isTauri } from '@tauri-apps/api/core';
import { open, save } from '@tauri-apps/plugin-dialog';
import appIcon from './assets/app-icon.png';
import './styles.css';

type Recipe = {version:number;operation:string;folder_template:string;filename_template:string;photo_folder:string;video_folder:string;separate_video:boolean;project:string;folder_tags:boolean;selected_folders:string[];excluded_folders:string[];keywords:string[];camera_tags:boolean;filesystem_date_fallback:boolean};
type Item = {id:number;source:string;destination:string;status:string;keywords:string[];warning:string|null;error:string|null;hash:string|null;size:number;kind:string;companions:{path:string;extension:string;hash:string}[];metadata:Record<string,unknown>};
type Snapshot = {database:string;job:{running:boolean;error:string|null;progress:{phase:string;completed:number;total:number;current:string}|null};summary:{files:number;bytes:number;statuses:Record<string,number>;scan_errors:number;scan_state:string|null;plan_state:string|null;output:string|null;recipe:Recipe|null}};
const defaults:Recipe={version:1,operation:'copy',folder_template:'{year}/{date}',filename_template:'{stem}',photo_folder:'Photos',video_folder:'Video',separate_video:true,project:'',folder_tags:true,selected_folders:[],excluded_folders:['DCIM','exports','Photos','Pictures'],keywords:[],camera_tags:false,filesystem_date_fallback:false};
const initial:Snapshot={database:'',job:{running:false,error:null,progress:null},summary:{files:0,bytes:0,statuses:{},scan_errors:0,scan_state:null,plan_state:null,output:null,recipe:null}};
const steps=['Sources','Scan','Recipe','Review','Export'];
const icons:Record<string,React.ReactNode>={
  folder:<><path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10H3Z"/></>,
  scan:<><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M7 12h10"/></>,
  sliders:<><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/></>,
  grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
  export:<><path d="M12 16V3m-5 5 5-5 5 5M4 14v7h16v-7"/></>,
  sun:<><circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/></>,
  moon:<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>,
  screen:<><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/></>,
  plus:<path d="M12 5v14M5 12h14"/>,
  arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,
  check:<path d="m5 12 4 4L19 6"/>,
  leaf:<><path d="M20 3C7 2 2 8 5 15s16 4 15-12ZM5 21 16 8"/></>,
  image:<><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="2"/><path d="m3 17 6-5 4 3 4-6 4 6"/></>,
};
function Icon({name,size=20}:{name:string;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]||icons.folder}</svg>}
function bytes(n:number){return n>=1e12?`${(n/1e12).toFixed(1)} TB`:n>=1e9?`${(n/1e9).toFixed(1)} GB`:n>=1e6?`${(n/1e6).toFixed(1)} MB`:`${(n/1e3).toFixed(0)} KB`}
function basename(path:string){return path.split('/').pop()||path}
function App(){
  const [theme,setTheme]=useState(localStorage.getItem('theme')||'system');
  const [updates,setUpdates]=useState(localStorage.getItem('updates')!=='false');
  const [step,setStep]=useState(0);const [sources,setSources]=useState<string[]>([]);const [output,setOutput]=useState('');
  const [recipe,setRecipe]=useState<Recipe>(defaults);const [state,setState]=useState(initial);const [error,setError]=useState('');
  const [items,setItems]=useState<Item[]>([]);const [filter,setFilter]=useState('');const [pages,setPages]=useState<number[]>([0]);
  const [folders,setFolders]=useState<string[]>([]);const [selected,setSelected]=useState<Item|null>(null);const [scanErrors,setScanErrors]=useState<{path:string;error:string}[]>([]);
  const [update,setUpdate]=useState<{configured:boolean;version?:string;body?:string}|null>(null);
  const [settings,setSettings]=useState(false);const [loaded,setLoaded]=useState(false);
  const busy=state.job.running;const scanned=state.summary.scan_state==='complete';const planned=state.summary.plan_state==='ready';
  const recipeMatchesPlan=JSON.stringify(Object.entries(recipe).sort())===JSON.stringify(Object.entries(state.summary.recipe||{}).sort());
  const counts=state.summary.statuses;const progress=state.job.progress;const desktop=isTauri();
  const patch=(change:Partial<Recipe>)=>setRecipe(r=>({...r,...change}));
  async function attempt(fn:()=>Promise<void>){setError('');try{await fn()}catch(e){setError(String(e))}}
  async function refresh(){if(!desktop)return;const next=await invoke<Snapshot>('snapshot');setState(next);return next;}
  async function loadRows(after=pages[pages.length-1],status=filter){if(desktop)setItems(await invoke<Item[]>('rows',{after,status:status||null}));}
  useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;apply();media.addEventListener('change',apply);localStorage.setItem('theme',theme);return()=>media.removeEventListener('change',apply)},[theme]);
  useEffect(()=>{if(!desktop){setLoaded(true);return;}attempt(async()=>{const s=await refresh();if(s){if(s.summary.recipe)setRecipe(s.summary.recipe);if(s.summary.output)setOutput(s.summary.output);if(s.summary.plan_state==='ready')setStep(3);else if(s.summary.scan_state)setStep(1);}setLoaded(true)});const timer=setInterval(()=>refresh().catch(e=>setError(String(e))),1200);return()=>clearInterval(timer)},[]);
  useEffect(()=>{localStorage.setItem('updates',String(updates));if(updates&&desktop)invoke<typeof update>('check_update').then(setUpdate).catch(()=>{/* Offline startup is normal. */})},[updates]);
  useEffect(()=>{if(desktop&&!busy){loadRows().catch(e=>setError(String(e)));if(scanned)invoke<string[]>('folder_candidates').then(setFolders).catch(e=>setError(String(e)));}},[busy,planned,filter,pages.length]);
  async function chooseSources(){if(!desktop){setError('Open the desktop app to choose local folders.');return;}const paths=await open({directory:true,multiple:true,title:'Choose source folders'});if(paths)setSources(old=>[...new Set([...old,...(Array.isArray(paths)?paths:[paths])])]);}
  async function chooseOutput(){const path=await open({directory:true,title:'Choose output folder'});if(typeof path==='string')setOutput(path);}
  async function start(action:string){await invoke('start',{action,sources,output,recipe});await refresh();}
  async function report(){const path=await save({defaultPath:'photo-hat-report.jsonl',filters:[{name:'JSON Lines report',extensions:['jsonl']}]});if(path)await invoke('save_report',{path});}
  async function resolve(hash:string,decision:string){await invoke('resolve',{hash,decision});await refresh();await loadRows();setSelected(null);}
  async function newSession(){await invoke('new_session');setSources([]);setOutput('');setItems([]);setPages([0]);setFilter('');setStep(0);await refresh();}
  const completed=counts.done||0;const total=state.summary.files-(counts.duplicate||0);
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><img src={appIcon} alt=""/></div><div>Photo Sorting Hat<span>A place for every frame.</span></div></div>
      <div className="nav-label">YOUR WORKFLOW</div>
      <nav>{steps.map((label,i)=><button key={label} className={`nav-item ${step===i?'active':''}`} onClick={()=>{setStep(i);setSettings(false)}}><Icon name={['folder','scan','sliders','grid','export'][i]}/><span>{label}</span><span className="nav-number">{i+1}</span></button>)}</nav>
      <div className="sidebar-bottom"><div className="offline-note"><span className="status-dot"/> Local processing<span>Your archive stays with you.</span></div><button className="quiet sidebar-action" disabled={busy||!desktop} onClick={()=>attempt(newSession)}><Icon name="plus" size={17}/>New archive session</button><button className="quiet sidebar-action" onClick={()=>setSettings(s=>!s)}><Icon name="sliders" size={17}/>Preferences</button><div className="theme-switch" aria-label="Color theme">{(['light','dark','system'] as const).map((t,i)=><button key={t} title={`${t} theme`} aria-label={`${t} theme`} aria-pressed={theme===t} className={theme===t?'selected':''} onClick={()=>setTheme(t)}><Icon name={['sun','moon','screen'][i]} size={17}/></button>)}</div><div className="version">PHOTO SORTING HAT <span>v0.1.0 · Preview</span></div></div>
    </aside>
    <main>
      <header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>{settings?'Preferences':steps[step]}</strong></div><div className="topbar-right"><span className="local-pill"><Icon name="leaf" size={14}/>Offline-first</span><span className="avatar">PS</span></div></header>
      <div className="page">
        {!desktop&&<div className="notice">Interface preview · Open the desktop app to organize files on your computer.</div>}
        {(error||state.job.error)&&<div role="alert" className="notice error"><strong>Needs attention</strong><span>{error||state.job.error}</span><button className="quiet" onClick={()=>setError('')}>×</button></div>}
        {update?.version&&<div className="notice"><span>Version {update.version} is available.</span><button disabled={busy} onClick={()=>attempt(async()=>{await invoke('install_update')})}>Install & restart</button></div>}
        {settings?<>
          <div className="page-heading"><div className="eyebrow">MAKE IT YOURS</div><h1>A little more your style.</h1><p>Set the mood, manage updates, and return to a saved archive.</p></div>
          <section className="panel settings-panel"><h2>Appearance</h2><div className="segmented">{['light','dark','system'].map(t=><button className={theme===t?'selected':''} key={t} onClick={()=>setTheme(t)}>{t==='light'?'Day':t==='dark'?'Night':'Follow system'}</button>)}</div><h2>Updates</h2><Toggle checked={updates} onChange={setUpdates} label="Check for updates at launch" description="Checks GitHub when online. Installation always waits for your approval and an idle app."/><button className="secondary" disabled={!desktop} onClick={()=>attempt(async()=>{const result=await invoke<typeof update>('check_update');setUpdate(result);if(!result?.configured)setError('Release endpoint and signing key will be configured when the GitHub repository is connected.');else if(!result.version)setError('You’re on the latest available version.');})}>Check now</button><h2>Saved sessions</h2><p className="muted path">{state.database||'Sessions are stored locally by the desktop app.'}</p><button className="secondary" disabled={busy||!desktop} onClick={()=>attempt(async()=>{const path=await open({filters:[{name:'Archive session',extensions:['sqlite']}]});if(typeof path==='string'){await invoke('open_session',{path});const next=await refresh();if(next?.summary.recipe)setRecipe(next.summary.recipe);setSettings(false);setStep(3);}})}>Open archive session</button></section>
        </>:<>
          <div className="step-trail">{steps.map((label,i)=><React.Fragment key={label}><button onClick={()=>setStep(i)} className={i===step?'current':i<step?'past':''}><span>{i<step?<Icon name="check" size={12}/>:i+1}</span>{label}</button>{i<4&&<span className="trail-line"/>}</React.Fragment>)}</div>
          {step===0&&<>
            <div className="page-heading"><div className="eyebrow">LESS SEARCHING. MORE CREATING.</div><h1>Every frame.<br/><em>In its right place.</em></h1><p>Bring scattered folders together into an organized archive.<br/>Your photos, their stories, all the details intact.</p></div>
            <div className="source-grid"><section className="panel source-panel"><div className="panel-heading"><div className="icon-tile"><Icon name="folder"/></div><span className="small-label">01 / INPUT</span></div><h2>Where are your originals?</h2><p>Add folders from your Mac, external drives,<br/>or a mounted archive.</p><button className="drop-zone" disabled={busy||!!state.summary.scan_state} onClick={()=>attempt(chooseSources)}><span className="circle-plus"><Icon name="plus"/></span><strong>Choose source folders</strong><span>RAW, JPEG, HEIC, TIFF, video & more</span></button>{sources.length>0&&<div className="source-list">{sources.map(s=><div key={s}><Icon name="folder" size={16}/><span title={s}>{s}</span><button aria-label={`Remove ${s}`} disabled={busy} onClick={()=>setSources(old=>old.filter(x=>x!==s))}>×</button></div>)}</div>}</section>
            <section className="panel source-panel"><div className="panel-heading"><div className="icon-tile warm"><Icon name="export"/></div><span className="small-label">02 / OUTPUT</span></div><h2>Give your archive a home.</h2><p>Choose a destination. We’ll build the folder<br/>structure from your recipe.</p><button className="destination-picker" disabled={busy||!!state.summary.scan_state||!desktop} onClick={()=>attempt(chooseOutput)}><Icon name="folder" size={23}/><span>{output?<><strong>{basename(output)}</strong><small>{output}</small></>:<><strong>Choose destination</strong><small>A folder with room to grow</small></>}</span><Icon name="arrow" size={18}/></button><div className="mini-tree"><div><Icon name="folder" size={15}/><strong>Your archive</strong></div><div className="tree-child"><span>├</span><Icon name="folder" size={14}/>Photos <span className="muted">/ 2024 / 2024-07-18</span></div><div className="tree-child"><span>└</span><Icon name="folder" size={14}/>Video <span className="muted">/ 2024 / 2024-07-18</span></div></div><div className="safe-note"><Icon name="check" size={15}/>Copy by default. Verified moves available.</div></section></div>
            <div className="feature-strip"><div><Icon name="scan"/><span><strong>Metadata does the work</strong><small>Organized by capture date, not guesswork.</small></span></div><div><Icon name="grid"/><span><strong>Lightroom-ready tags</strong><small>Carry your folder names into your catalog.</small></span></div><div><Icon name="leaf"/><span><strong>Made for your archive</strong><small>Local processing. No image uploads.</small></span></div></div>
            <footer className="action-bar"><span>{sources.length?`${sources.length} source folder${sources.length===1?'':'s'} selected`:'Start with one folder, or your whole archive.'}</span><button className="primary" disabled={!sources.length||!output||busy||!desktop||!!state.summary.scan_state} onClick={()=>attempt(async()=>{await start('scan');setStep(1)})}>Scan folders<Icon name="arrow" size={17}/></button></footer>
          </>}
          {step===1&&<>
            <Heading eyebrow="GETTING TO KNOW YOUR ARCHIVE" title={busy?'Reading the stories in your files.':scanned?'Your archive, at a glance.':'Ready when you are.'} description="Read capture dates and camera details, then compare file hashes to find exact duplicates."/>
            <div className="stats"><Stat label="Files indexed" value={state.summary.files.toLocaleString()} icon="image"/><Stat label="Archive size" value={bytes(state.summary.bytes)} icon="folder"/><Stat label="Scan issues" value={String(state.summary.scan_errors)} icon="scan"/></div>
            <section className="panel"><JobProgress progress={progress} busy={busy}/><p className="muted">No originals are changed during scanning. You can stop and resume from this session.</p><div className="button-row">{busy?<button className="secondary" onClick={()=>attempt(async()=>{await invoke('cancel')})}>Stop safely</button>:state.summary.scan_state&&!state.summary.plan_state&&<button className="secondary" onClick={()=>attempt(()=>start('resume'))}>Resume scan</button>}{state.summary.scan_errors>0&&<button className="secondary" onClick={()=>attempt(async()=>setScanErrors(await invoke('scan_errors',{after:''})))}>View scan issues</button>}</div>{scanErrors.map(e=><div className="scan-error" key={e.path}><strong>{e.path}</strong><span>{e.error}</span></div>)}</section>
            <footer className="action-bar"><button className="quiet" onClick={()=>setStep(0)}>Back to sources</button><button className="primary" disabled={!scanned||busy} onClick={()=>setStep(2)}>Build your recipe<Icon name="arrow" size={17}/></button></footer>
          </>}
          {step===2&&<>
            <Heading eyebrow="A SYSTEM THAT MAKES SENSE TO YOU" title="Your archive. Your recipe." description="Choose the structure once. Preview every destination before anything changes."/>
            <div className="recipe-layout"><div className="recipe-fields"><section className="panel"><h2>Transfer mode</h2><div className="mode-cards">{['copy','move'].map(mode=><button key={mode} disabled={busy} className={recipe.operation===mode?'selected':''} onClick={()=>patch({operation:mode})}><strong>{mode==='copy'?'Copy originals':'Move originals'}</strong><span>{mode==='copy'?'Keep sources in place':'Remove sources after verification'}</span></button>)}</div>{recipe.operation==='move'&&<p className="move-note">Verified moves use fast linking where possible. Unselected duplicates and shared sidecars stay in the source folders.</p>}<h2>Folder structure</h2><Field label="Folder recipe" value={recipe.folder_template} onChange={v=>patch({folder_template:v})}/><div className="token-list">{['year','month','date','camera','make','project','source_folder'].map(t=><button key={t} onClick={()=>patch({folder_template:`${recipe.folder_template}/{${t}}`})}>{`{${t}}`}</button>)}</div><div className="field-grid"><Field label="Photo folder" value={recipe.photo_folder} onChange={v=>patch({photo_folder:v})}/><Field label="Video folder" value={recipe.video_folder} onChange={v=>patch({video_folder:v})}/></div><Toggle checked={recipe.separate_video} onChange={v=>patch({separate_video:v})} label="Keep videos in a separate folder" description="Uses the same date and naming recipe."/><Field label="Filename recipe" value={recipe.filename_template} onChange={v=>patch({filename_template:v})} hint="{stem} keeps the original name. Try {timestamp}_{stem}. Extension is preserved."/><Field label="Project name" value={recipe.project} onChange={v=>patch({project:v})} hint="Used wherever you include {project}."/></section>
            <section className="panel"><h2>Keywords that travel with your photos</h2><ListField label="Add keywords (comma separated)" values={recipe.keywords} onChange={keywords=>patch({keywords})}/><Toggle checked={recipe.folder_tags} onChange={v=>patch({folder_tags:v})} label="Use existing folder names as keywords" description="Choose useful ancestors and leave generic folders out."/>{recipe.folder_tags&&<><ListField label="Exclude folder names" values={recipe.excluded_folders} onChange={excluded_folders=>patch({excluded_folders})}/><p className="muted small">All non-excluded ancestors are selected by default. Select individual names to narrow them.</p><div className="folder-chips">{folders.map(f=><button key={f} className={recipe.selected_folders.includes(f)?'selected':''} onClick={()=>patch({selected_folders:recipe.selected_folders.includes(f)?recipe.selected_folders.filter(x=>x!==f):[...recipe.selected_folders,f]})}>{f}</button>)}</div>{!!recipe.selected_folders.length&&<button className="quiet" onClick={()=>patch({selected_folders:[]})}>Use all non-excluded folders</button>}</>}<Toggle checked={recipe.camera_tags} onChange={v=>patch({camera_tags:v})} label="Add camera and lens keywords"/><Toggle checked={recipe.filesystem_date_fallback} onChange={v=>patch({filesystem_date_fallback:v})} label="Use file modification date when capture date is missing" description="Off by default. Missing capture dates otherwise go to Undated."/></section></div>
            <aside className="recipe-preview panel"><span className="small-label">RECIPE EXAMPLE</span><div className="preview-file"><Icon name="image" size={30}/><strong>DSC_2048.CR3</strong><span>Captured July 18, 2024</span></div><div className="preview-arrow">↓</div><code>{recipe.photo_folder}/{recipe.folder_template.replaceAll('{year}','2024').replaceAll('{month}','07').replaceAll('{date}','2024-07-18').replaceAll('{camera}','Canon EOS R5').replaceAll('{make}','Canon').replaceAll('{project}',recipe.project||'Unknown').replaceAll('{source_folder}','Summer')}/{recipe.filename_template.replaceAll('{stem}','DSC_2048').replaceAll('{timestamp}','20240718_143022')}.CR3</code><div className="preview-companion">+ Matching .xmp with your keywords</div><hr/><p>Actual paths, tags, missing dates, and collisions appear in the next step.</p><div className="button-row vertical"><button className="secondary" disabled={!desktop} onClick={()=>attempt(async()=>{const path=await save({defaultPath:'my-recipe.json'});if(path)await invoke('save_recipe',{path,recipe})})}>Save recipe</button><button className="quiet" disabled={!desktop} onClick={()=>attempt(async()=>{const path=await open({filters:[{name:'Recipe',extensions:['json']}]});if(typeof path==='string')setRecipe(await invoke('load_recipe',{path}))})}>Load a recipe</button></div></aside></div>
            <footer className="action-bar"><span>Originals stay intact until a verified move completes.</span><button className="primary" disabled={!scanned||busy} onClick={()=>attempt(async()=>{await start('plan');setStep(3)})}>Preview destinations<Icon name="arrow" size={17}/></button></footer>
          </>}
          {(step===3||step===4)&&planned&&!recipeMatchesPlan&&<div className="notice">Your recipe has changed. Return to Recipe and preview destinations before exporting.</div>}
          {step===3&&<>
            <Heading eyebrow="A FINAL LOOK BEFORE THEY FIND A HOME" title="Everything in its place?" description="Review destinations and keywords. Conflicting duplicate sidecars need a decision before export."/>
            <div className="stats"><Stat label="Ready to export" value={String(counts.planned||0)} icon="check"/><Stat label="Duplicate copies retained" value={String(counts.duplicate||0)} icon="grid"/><Stat label="Need your review" value={String(counts.review||0)} icon="scan"/></div>
            {busy&&<section className="panel"><JobProgress busy={busy} progress={progress}/><button className="secondary" onClick={()=>attempt(async()=>{await invoke('cancel')})}>Stop safely</button></section>}
            <section className="panel table-panel"><div className="table-toolbar"><h2>Destination preview</h2><select aria-label="Filter files" value={filter} onChange={e=>{setFilter(e.target.value);setPages([0])}}><option value="">All files</option><option value="review">Needs review</option><option value="duplicate">Duplicates</option><option value="planned">Ready</option><option value="error">Errors</option><option value="done">Exported</option></select></div><div className="table-scroll"><table><thead><tr><th>FILE</th><th>DESTINATION / KEYWORDS</th><th>STATUS</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>setSelected(item)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setSelected(item)}}><td><div className="file-name"><Icon name={item.kind==='video'?'export':'image'} size={19}/><div><strong>{basename(item.source)}</strong><small>{bytes(item.size)} · {item.kind}</small></div></div></td><td><div className="destination-path" title={item.destination}>{item.destination.replace(`${state.summary.output}/`,'')}</div><div className="tags">{item.keywords.slice(0,4).map(k=><span key={k}>{k}</span>)}{item.keywords.length>4&&<span>+{item.keywords.length-4}</span>}</div></td><td><span className={`badge ${item.status}`}>{({planned:'Ready',duplicate:'Duplicate',review:'Review',done:'Exported',error:'Error',publishing:'Publishing',cleanup:'Verifying'} as Record<string,string>)[item.status]||item.status}</span></td></tr>)}</tbody></table>{!items.length&&<div className="empty-state"><Icon name="grid" size={32}/><h3>{planned?'No files in this view.':'Your preview will appear here.'}</h3><p>{planned?'Choose another filter to see your files.':'Scan your sources, then build a recipe to see every destination.'}</p></div>}</div><div className="pagination"><span>Up to 100 files per page · {state.summary.files.toLocaleString()} indexed</span><div><button disabled={pages.length===1} onClick={()=>setPages(p=>p.slice(0,-1))}>Previous</button><button disabled={items.length<100} onClick={()=>setPages(p=>[...p,items[items.length-1].id])}>Next</button></div></div></section>
            <footer className="action-bar"><button className="quiet" onClick={()=>setStep(2)}>Edit recipe</button><button className="primary" disabled={!planned||busy||!!counts.review||!recipeMatchesPlan} onClick={()=>setStep(4)}>Continue to export<Icon name="arrow" size={17}/></button></footer>
          </>}
          {step===4&&<>
            <Heading eyebrow="THE NEXT CHAPTER FOR YOUR ARCHIVE" title={completed===total&&total>0?'A new home for your frames.':'Ready for a fresh start.'} description={recipe.operation==='move'?'Move verified files to their new home. Original duplicates that are skipped stay where they are.':'Create an organized copy, with Lightroom metadata and a record of every source.'}/>
            <section className="panel export-panel"><div className="export-orbit"><Icon name={completed===total&&total>0?'check':'export'} size={40}/></div><h2>{busy?'Your archive is taking shape.':`${recipe.operation==='move'?'Move':'Copy'} to ${basename(state.summary.output||output)||'your destination'}`}</h2><p className="path muted">{state.summary.output||output||'Choose an output folder in Sources.'}</p><div className="export-numbers"><strong>{completed.toLocaleString()}<span> / {total.toLocaleString()}</span></strong><small>files verified and exported</small></div><JobProgress progress={progress} busy={busy}/><div className="button-row centered">{busy?<button className="secondary" onClick={()=>attempt(async()=>{await invoke('cancel')})}>Stop safely</button>:<button className="primary" disabled={!planned||!!counts.review||!total||(completed===total)||!recipeMatchesPlan} onClick={()=>attempt(()=>start('export'))}>{counts.error||completed?'Resume export':recipe.operation==='move'?'Move files after verification':'Start verified export'}<Icon name="arrow" size={17}/></button>}<button className="secondary" disabled={!planned||busy} onClick={()=>attempt(report)}>Save report</button></div>{!!counts.error&&<button className="quiet" onClick={()=>{setFilter('error');setPages([0]);setStep(3)}}>Review {counts.error} export errors</button>}<div className="safe-note"><Icon name="check" size={16}/>Checksums verified · Existing files never overwritten · Progress saved</div></section>
          </>}
        </>}
        <div className="page-footnote">Made for the photographs you’ll keep coming back to.</div>
      </div>
    </main>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-label="File details" className="detail-modal panel" onClick={e=>e.stopPropagation()}><button className="close-modal" aria-label="Close details" onClick={()=>setSelected(null)}>×</button><span className="small-label">FILE DETAILS</span><h2>{basename(selected.source)}</h2><label>Source</label><p className="path">{selected.source}</p><label>Destination</label><p className="path">{selected.destination}</p><label>Keywords</label><div className="tags">{selected.keywords.map(k=><span key={k}>{k}</span>)}</div>{selected.warning&&<p className="move-note">{selected.warning}</p>}{selected.error&&<p className="notice error">{selected.error}</p>}<label>Existing sidecars</label>{selected.companions.length?selected.companions.map(c=><p className="path small" key={c.path}>{c.path}<br/><span className="muted">SHA-256: {c.hash}</span></p>):<p className="muted">None</p>}<details><summary>Recorded metadata</summary><pre>{JSON.stringify(selected.metadata,null,2)}</pre></details>{selected.hash&&['review','duplicate','planned'].includes(selected.status)&&<><h3>Duplicate group decision</h3><p className="muted">“Use first” keeps the earliest indexed representative’s sidecar edits and merged keywords. Other copies remain at their sources. Compare the group’s files before choosing.</p><div className="button-row"><button disabled={busy} className="primary" onClick={()=>attempt(()=>resolve(selected.hash!,'keep_all'))}>Keep all separately</button><button disabled={busy} className="secondary" onClick={()=>attempt(()=>resolve(selected.hash!,'use_first'))}>Use first representative</button></div></>}</section></div>}
    {!loaded&&desktop&&<div className="loading">Opening your archive…</div>}
  </div>
}
function Heading({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-heading compact"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>}
function Field({label,value,onChange,hint}:{label:string;value:string;onChange:(v:string)=>void;hint?:string}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/>{hint&&<small>{hint}</small>}</label>}
function ListField({label,values,onChange}:{label:string;values:string[];onChange:(v:string[])=>void}){const [text,setText]=useState(values.join(", "));useEffect(()=>setText(values.join(", ")),[JSON.stringify(values)]);return <label className="field"><span>{label}</span><input value={text} onChange={e=>setText(e.target.value)} onBlur={()=>onChange(text.split(",").map(x=>x.trim()).filter(Boolean))}/></label>}
function Toggle({checked,onChange,label,description}:{checked:boolean;onChange:(v:boolean)=>void;label:string;description?:string}){return <label className="toggle-row"><span><strong>{label}</strong>{description&&<small>{description}</small>}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle"/></label>}
function Stat({label,value,icon}:{label:string;value:string;icon:string}){return <section className="panel stat"><Icon name={icon}/><strong>{value}</strong><span>{label}</span></section>}
function JobProgress({progress,busy}:{progress:Snapshot['job']['progress'];busy:boolean}){const percent=progress?.total?Math.min(100,100*progress.completed/progress.total):0;return <div className="job-progress"><div className="progress-label"><strong>{progress?.phase||'Waiting to begin'}</strong><span>{busy?'Working locally':progress?'Saved':'All set'}</span></div><div className={`progress-track ${busy&&!percent?'indeterminate':''}`}><div style={{width:`${percent}%`}}/></div><p className="path muted small" title={progress?.current}>{progress?.current||'Your session is saved automatically.'}</p></div>}
createRoot(document.getElementById('root')!).render(<App/>);
